---
- name: Ensure Microsoft .Net Framework 4.6.2 is installed
  win_chocolatey:
    name: dotnet4.6.2

- name: Create PowerShell folder
  win_file:
    path: '{{powershellPath}}'
    state: directory
  
- name: Download powershell scritps
  win_get_url:
    url: 'https://github.com/mehrdud/ansible/blob/master/powershellScripts/backup.ps1'
    dest: '{{powershellPath}}\backup.ps1'