targetEnvironment: "live"

powershellPath: "c:\\inetpub\\powershellScripts"
backupPath: "C:\\inetpub\\00Backup"
 
deploymentId: "{{lookup('pipe','date +%Y%m%d%H%M')}}"   
        
deploymentPackages:  
  - name: 'DarkCocoaPortal'
    folder: 'C:\inetpub\wwwroot\DarkCocoaPortal'
    ip: ''
    port: 5050
    packageName: "DarkCocoaPortal.zip"    
    sourcePackage: "https://github.com/mehrdud/DarkCocoa/raw/master/DeploymentPackages/DarkCocoaPortal/DarkCocoaPortal.zip"
    sourceConfigFile: "https://raw.githubusercontent.com/mehrdud/DarkCocoa/master/DeploymentPackages/DarkCocoaPortal/Web.live.config"
    
  - name: 'DarkCocoaReports'
    folder: 'C:\inetpub\wwwroot\DarkCocoaReports'
    ip: ''
    port: 5060
    packageName: "DarkCocoaReports.zip"    
    sourcePackage: "https://github.com/mehrdud/DarkCocoa/raw/master/DeploymentPackages/DarkCocoaReports/DarkCocoaReports.zip"    
    sourceConfigFile: "https://raw.githubusercontent.com/mehrdud/DarkCocoa/master/DeploymentPackages/DarkCocoaReports/Web.live.config"