---
- name: Ensure Microsoft .Net Framework 4.6.2 is installed
  win_chocolatey:
    name: dotnet4.6.2

- name: Ensure "Web Server (IIS)" feature is installed
  win_feature:
    name: Web-Server
    state: present
    include_sub_features: True
    include_management_tools: True    