--- 
- hosts: web

  tasks:
  - name: ping servers
    win_ping:   
  
  - name: Ensure "Web Server (IIS)" feature is installed
    win_feature: 
      name: Web-Server
      state: present 
      include_sub_features: True
      include_management_tools: True 